create table episodes (
    uni_id uuid primary key DEFAULT uuid_generate_v4 () UNIQUE,
    uid text references users(uid) not null,
    show_title text, 
    project_id uuid references projects(id) ON DELETE CASCADE,
    episode_num text,
    episode_title text,
    author text,
    logline text,
    genre text,
    projformat text,
    budget text,
    timeperiod text,
    similarepisodes text,
    framework text,
    bottle_episode text,
    visible boolean,
    show_hidden boolean,
    date_created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    shared boolean
)