create table SharedProjects (
    uni_id generated by default as identity,
    id uuid references projects(id) ON DELETE CASCADE,
    title text, 
    author text,
    logline text,
    genre text,
    projformat text,
    budget text,
    timeperiod text,
    similarprojects text,
    framework text,
    visible boolean,
    show_hidden boolean,
    shared_by_uid text references users(uid) not null,
    shared_with_uid text references users(uid) not null,
    permission text
)