INSERT INTO cat (step_name, step_desc, act)
values
('Opening Image', 'A single scene beat that shows a “before” snapshot of the protagonist and the flawed world that he or she lives in.', '1'),
('Theme Stated', 'A single scene beat in which a statement is made by someone (other than the protagonist) that hints at what the protagonist will learn before the end of the story.', '1'),
('Setup', 'A multi-scene beat in which the reader gets to see what the protagonist’s life and the world are like–flaws and all. It’s also where important supporting characters and the protagonist’s initial goal (or the thing the protagonist thinks will fix his or her life) is introduced.', '1'),
('Catalyst', 'A single scene beat in which a life-changing event happens to the protagonist and catapults him or her into a new world or a new way of thinking. In other words, after this moment, there’s no going back to the “normal world” introduced in the setup.', '1'),
('Debate', 'A multi-scene beat where the protagonist debates what he or she will do next. Usually, there is some kind of question haunting them like, “should I do this?” or “should I do that?” The purpose of this beat is to show that the protagonist is reluctant to change for one reason or another.', '1'),
('Break Into Two', 'A single scene beat in which the protagonist decides to accept the call to adventure, leave their comfort zone, try something new, or to venture into a new world or way of thinking. It’s the bridge between the beginning (Act 1) and middle (Act 2) of the story.', '1'),
('B Story', 'A single scene beat that introduces a new character or characters who will ultimately serve to help the hero learn the theme (or lesson) of the story. This character could be a love interest, a nemesis, a mentor, a family member, a friend, etc.', '2'),
('Fun and Games', 'A multi-scene beat where the reader gets to see the protagonist either shining or floundering in their new world. In other words, they are either loving their new world or hating it.', '2'),
('Midpoint', ' A single scene beat where the fun and games section either culminates in a “false victory” (if your protagonist has been succeeding thus far) or a “false defeat” (if your protagonist has been floundering thus far) or a. In romance novels, this could be a kiss (or more), a declaration of love, or a marriage proposal. In a mystery or thriller, this could be a game-changing plot twist or a sudden ticking clock that ups the ante. This could even be a celebration or the first big public outing where the protagonist officially declares themselves a part of their new world. Whatever happens during this beat, it should raise the stakes and push the protagonist toward making a real change before moving forward.', '2'),
('Bad Guys Close In', 'If the protagonist had a “false victory” at the Midpoint, this multi-scene beat would be a downward path where things get worse and worse for him or her. On the other hand, if the Midpoint was a “false defeat,” this section will be an upward path where things get better and better. Regardless of the path your protagonist takes during this multi-scene beat, his or her deep-rooted fear or false-belief (their internal bad guys) and the antagonist (external bad guys) are closing in.', '2'),
('All is Lost', ' A single scene beat where something happens, that when combined with the threat of the bad guys closing in, pushes your protagonist to their lowest point.', '2'),
('Dark Night of the Soul', 'A multi-scene beat in which the protagonist takes time to process everything that’s happened so far. This is his or her darkest hour—the moment right before he or she figures out the solution to their big problem and learns the theme or life lesson of the story.', '2'),
('Break Into Three ', 'A single scene beat where the protagonist realizes what he or she must do to fix not only the external story problems but more importantly, their internal problems as well.', '2'),
('Finale ', 'A multi-scene beat where the protagonist proves they have learned the story’s theme and acts on the plan he or she made in the Break Into Three scene. A great finale has five parts:', '3'),
('Final Image', 'A single scene beat that shows the reader an “after” snapshot of your protagonist’s life and how much he or she has changed since the beginning of the story.', '3')
