insert into characters(user_id, project_name, name, age, gender, details)
values
('hTbqcYvNe7dGhxXaphw3UEqNfep2', 'Seventeen West', 'Tara', 'mid 30s', 'Female', array['Bio', 'Want', 'Need']),
('hTbqcYvNe7dGhxXaphw3UEqNfep2', 'Seventeen West', 'Blake', '18', 'Male', array['Bio', 'Want', 'Need']),
('hTbqcYvNe7dGhxXaphw3UEqNfep2', 'Seventeen West', 'Adriene', 'mid 30s', 'Female', array['Bio', 'Want', 'Need']),
('hTbqcYvNe7dGhxXaphw3UEqNfep2', 'Seventeen West', 'Spencer', '16', 'Male', array['Bio', 'Want', 'Need']),
('hTbqcYvNe7dGhxXaphw3UEqNfep2', 'Seventeen West', 'Mary', 'mid 30s', 'Female', array['Bio', 'Want', 'Need']),
('hTbqcYvNe7dGhxXaphw3UEqNfep2', 'Below The Line', 'Christian', 'early 30s', 'Male', array['Bio', 'Want', 'Need']),
('hTbqcYvNe7dGhxXaphw3UEqNfep2', 'Below The Line', 'Malcolm', 'early 30s', 'Male', array['Bio', 'Want', 'Need']),
('hTbqcYvNe7dGhxXaphw3UEqNfep2', 'Below The Line', 'Jenny', 'late 20s', 'Female', array['Bio', 'Want', 'Need']),
('hTbqcYvNe7dGhxXaphw3UEqNfep2', 'Below The Line', 'Lisa', 'early 30s', 'Female', array['Bio', 'Want', 'Need']),
('hTbqcYvNe7dGhxXaphw3UEqNfep2', 'Monsoon Season', 'Louella', 'mid 30s', 'Female', array['Bio', 'Want', 'Need']),
('hTbqcYvNe7dGhxXaphw3UEqNfep2', 'Monsoon Season', 'Ocampo', 'late 30s', 'Male', array['Bio', 'Want', 'Need']),
('hTbqcYvNe7dGhxXaphw3UEqNfep2', 'Monsoon Season', 'Danilo', 'late 30s', 'Male', array['Bio', 'Want', 'Need']),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Cult Movie', 'Roberta', 'mid 30s', 'Female', array['Bio', 'Want', 'Need']),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Cult Movie', 'James', '18', 'Male', array['Bio', 'Want', 'Need']),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Cult Movie', 'Lacey', 'mid 30s', 'Female', array['Bio', 'Want', 'Need']),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Cult Movie', 'Sam', '16', 'Male', array['Bio', 'Want', 'Need']),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Cult Movie', 'Mildred', 'mid 30s', 'Female', array['Bio', 'Want', 'Need']),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Catholic School Movie', 'Chris', 'early 30s', 'Male', array['Bio', 'Want', 'Need']),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Catholic School Movie', 'Martin', 'early 30s', 'Male', array['Bio', 'Want', 'Need']),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Catholic School Movie', 'Jennifer', 'late 20s', 'Female', array['Bio', 'Want', 'Need']),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Catholic School Movie', 'Laura', 'early 30s', 'Female', array['Bio', 'Want', 'Need']),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Home Shopping Murder', 'Sarah', 'mid 30s', 'Female', array['Bio', 'Want', 'Need']),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Home Shopping Murder', 'Fred', 'late 30s', 'Male', array['Bio', 'Want', 'Need']),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Home Shopping Murder', 'Dane', 'late 30s', 'Male', array['Bio', 'Want', 'Need'])
