INSERT INTO hero (step_name, step_desc, act)
values
('Ordinary World', 'This section explores the current state of the hero''s everyday life. This is where the hero is grounded in their humanity and we learn important details about how they see themselves and their place in the world.', '1'),
('Call to Adventure', 'The hero recieves a call to action. They are presented with something they must do that will take them out of their ordinary world and regular routine.', '1'),
('Refusal of the Call', 'Some hero''s are up to the challenge the call presents and are eager to go for it. Often times the hero is intiiallty reluctant and refueses the call at first. They may have to overcome fears or feelings inadequacy. Somtimes they need extra motivation, often in the form of a reminder of what they are fighting for.', '1'),
('Meeting the Mentor', 'Before embarking on their journey the hero meets a mentor figure who prepares them for the road ahead.', '1'),
('Crossing the Threshold', 'The hero has begun their journey and left the ordinary world. They enter a world that is distinct from the world they are used to. This special world has its own set of rules and challenges.', '1'),
('Tests, Allies, Enemies', 'The hero is tested in the special world. They must adapt to the rules of the special world. Here they will encounter allies and enemies and must discern who can and cannot be trusted. All of the obstacles in this stage give the audience more insight into who the hero is and they prepare the hero for the largest challenge ahead.', '2'),
('Approach to the Inmost Cave', 'The hero must prepare face a conflict that they have yet to deal with. The inmost cave can manifest itself as a physcial location where there are extrememe dangers or an inner conflict the hero has been avoiding.', '2'),
('Ordeal', 'This is the greatest challenge the hero has yet to face. They must call upon everything they have learned up to this point in order to succeed. There is more at stake now then there has ever been. The hero faces some form of death here in order to be reborn stronger and wiser.', '2'),
('Reward', 'The hero has defeated their opponent and attains the reward. This could come in the form of a physical object or new insight into their internal conflict.', '2'),
('The Road Back', 'The hero prepares to return to the ordinary world but before they can return they often have to be pushed back into the oridinary world. Returning is a choice and the hero often must choose between their superficial goals and a greater good.', '3'),
('Resurrection', 'Here the hero faces their final battle with the oppoent. The opponent will make one last stand in an attempt to derail the hero''s progress. The hero must find new resolve in order to complete their journey.', '3'),
('Return with the Elixir', 'In the final stage the hero returns to the oridinary world a changed person. They may have a physical object or new knowledge that will change the lives of those they left behind. The hero now has a new relationship with their ordinary world and how they fit in it.', '3')
