INSERT INTO anatomy (step_name, step_desc, act)
values
('Weakness and Need', 'The hero has a profound weakness that is causing them to suffer. The need refers to what the hero must fulfill in order to become complete. Satifying the need should include overcoming their inherent weakness. Robust characters have both a moral and psychological need; something they need address that his hurting their own progress and something they do that is hurting others around them.', '1'),
('Desire', 'This is what the hero wants and is not to be confused with what the hero needs. The desire is a plot centric goal. Although the desire and need are not the same, well structure stories have their character need satisfied by chasing the goal.', '1'),
('Opponent', 'The opponent should not be seens as "the bad guy" but instead they should be used in terms of their story function. An opponent should not want to simply stop the hero from achieving their goal. The opponent should also be after the same goal as the hero. By thinking of the opponnet this way you ensure that the hero and opponent come into direct conflict.', '2'),
('Plan', 'The plan is what the hero decides to DO in order to achieve the goal. The plan is linked directly to the desire and opponent and should focus on achieving the desire and defeating the opponent.', '2'),
('Battle', 'During the execution of the plan the hero and the opponent have many smaller encounters and rack up wins and losses. The battle is the final and largest confrontation that decides which of them will ultimately achieve the goal.', '2'),
('Self-Revelation', 'The result of the battle causes the hero to have a psychological and moral self revelation.', '3'),
('New Equilibrium', 'The hero''s world returns to normal and they have either ascended to a higer level or fallen to a lower one as a result of the events of the story', '3')
