insert into scenes (uid, project_name, act, step_name, scene_heading, thesis, antithesis, synthesis)
values
('hTbqcYvNe7dGhxXaphw3UEqNfep2', 'Seventeen West', 'Act 1', 'Ordinary World', 'INT. BAR - NIGHT', 'thesis statement 1', 'antithesis statement 1', 'synthesis statement 3'),
('hTbqcYvNe7dGhxXaphw3UEqNfep2', 'Seventeen West', 'Act 1', 'Ordinary World', 'INT. HOTEL - DAY', 'thesis statement 1', 'antithesis statement 1', 'synthesis statement 3'),
('hTbqcYvNe7dGhxXaphw3UEqNfep2', 'Seventeen West', 'Act 1', 'Ordinary World', 'EXT. BAR - NIGHT', 'thesis statement 1', 'antithesis statement 1', 'synthesis statement 3'),
('hTbqcYvNe7dGhxXaphw3UEqNfep2', 'Seventeen West', 'Act 1', 'Ordinary World', 'INT. HOUSE - EVENING', 'thesis statement 1', 'antithesis statement 1', 'synthesis statement 3'),
('hTbqcYvNe7dGhxXaphw3UEqNfep2', 'Seventeen West', 'Act 2', 'Tests, Allies, Enemies', 'INT. HOME - DAY', 'thesis statement 2', 'antithesis statement 2', 'synthesis statement 3'),
('hTbqcYvNe7dGhxXaphw3UEqNfep2', 'Seventeen West', 'Act 2', 'Tests, Allies, Enemies', 'EXT. OFFICE - DAY', 'thesis statement 2', 'antithesis statement 2', 'synthesis statement 3'),
('hTbqcYvNe7dGhxXaphw3UEqNfep2', 'Seventeen West', 'Act 2', 'Tests, Allies, Enemies', 'INT. HOME - NIGHT', 'thesis statement 2', 'antithesis statement 2', 'synthesis statement 3'),
('hTbqcYvNe7dGhxXaphw3UEqNfep2', 'Seventeen West', 'Act 2', 'Tests, Allies, Enemies', 'EXT. PARK - DAY', 'thesis statement 2', 'antithesis statement 2', 'synthesis statement 3'),
('hTbqcYvNe7dGhxXaphw3UEqNfep2', 'Seventeen West', 'Act 2', 'Tests, Allies, Enemies', 'INT. HOME - NIGHT', 'thesis statement 2', 'antithesis statement 2', 'synthesis statement 3'),
('hTbqcYvNe7dGhxXaphw3UEqNfep2', 'Seventeen West', 'Act 3', 'The Road Back', 'INT. HOUSE - CONTINUOUS', 'thesis statement 3', 'antithesis statement 2', 'synthesis statement 3'),
('hTbqcYvNe7dGhxXaphw3UEqNfep2', 'Seventeen West', 'Act 3', 'The Road Back', 'EXT. HOTEL - NIGHT', 'thesis statement 3', 'antithesis statement 2', 'synthesis statement 3'),
('hTbqcYvNe7dGhxXaphw3UEqNfep2', 'Seventeen West', 'Act 3', 'The Road Back', 'INT. HOUSE - CONTINUOUS', 'thesis statement 3', 'antithesis statement 2', 'synthesis statement 3'),
('hTbqcYvNe7dGhxXaphw3UEqNfep2', 'Seventeen West', 'Act 3', 'The Road Back', 'EXT. OFFICE - DAY', 'thesis statement 3', 'antithesis statement 2', 'synthesis statement 3'),
('hTbqcYvNe7dGhxXaphw3UEqNfep2', 'Monsoon Season', 'Act 2', 'Tests, Allies, Enemies', 'EXT. MALL - DAY', 'thesis statement 2', 'antithesis statement 2', 'synthesis statement 3'),
('hTbqcYvNe7dGhxXaphw3UEqNfep2', 'Monsoon Season', 'Act 3', 'The Road Back', 'INT. BOAT - CONTINUOUS', 'thesis statement 3', 'antithesis statement 2', 'synthesis statement 3'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Cult Movie', 'Act 1', 'Ordinary World', 'INT. HOUSE - DAY', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Cult Movie', 'Act 1', 'Ordinary World', 'EXT. OFFICE - NIGHT', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Cult Movie', 'Act 1', 'Ordinary World', 'INT. APARTMENT- CONTINUOUS', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Cult Movie', 'Act 1', 'Ordinary World', 'EXT. PARK - SAME', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Cult Movie', 'Act 2', 'Tests, Allies, Enemies', 'INT. SCHOOL - DAY', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Cult Movie', 'Act 2', 'Tests, Allies, Enemies', 'EXT. HOME - NIGHT', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Cult Movie', 'Act 2', 'Tests, Allies, Enemies', 'INT. OFFICE - CONTINUOUS', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Cult Movie', 'Act 2', 'Tests, Allies, Enemies', 'EXT. PARK - SAME', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Cult Movie', 'Act 3', 'The Road Back', 'INT. BAR - DAY', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Cult Movie', 'Act 3', 'The Road Back', 'EXT. BAR - NIGHT', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Cult Movie', 'Act 3', 'The Road Back', 'INT. RESTAURANT - CONTINUOUS', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Cult Movie', 'Act 3', 'The Road Back', 'EXT. HOME - SAME', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Catholic School Movie', 'Act 1', 'Ordinary World','INT. HOUSE - DAY', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Catholic School Movie', 'Act 1', 'Ordinary World','EXT. OFFICE - NIGHT', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Catholic School Movie', 'Act 1', 'Ordinary World','INT. APARTMENT- CONTINUOUS', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Catholic School Movie', 'Act 1', 'Ordinary World','EXT. PARK - SAME', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Catholic School Movie', 'Act 2', 'Tests, Allies, Enemies', 'INT. SCHOOL - DAY', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Catholic School Movie', 'Act 2', 'Tests, Allies, Enemies', 'EXT. HOME - NIGHT', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Catholic School Movie', 'Act 2', 'Tests, Allies, Enemies', 'INT. OFFICE - CONTINUOUS', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Catholic School Movie', 'Act 2', 'Tests, Allies, Enemies', 'EXT. PARK - SAME', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Catholic School Movie', 'Act 3', 'The Road Back', 'INT. BAR - DAY', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Catholic School Movie', 'Act 3', 'The Road Back', 'EXT. BAR - NIGHT', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Catholic School Movie', 'Act 3', 'The Road Back', 'INT. RESTAURANT - CONTINUOUS', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Catholic School Movie', 'Act 3', 'The Road Back', 'EXT. HOME - SAME', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Home Shopping Murder', 'Act 1', 'Ordinary World','INT. HOUSE - DAY', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Home Shopping Murder', 'Act 1', 'Ordinary World','EXT. OFFICE - NIGHT', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Home Shopping Murder', 'Act 1', 'Ordinary World','INT. APARTMENT- CONTINUOUS', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Home Shopping Murder', 'Act 1', 'Ordinary World','EXT. PARK - SAME', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Home Shopping Murder', 'Act 2', 'Tests, Allies, Enemies', 'INT. SCHOOL - DAY', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Home Shopping Murder', 'Act 2', 'Tests, Allies, Enemies', 'EXT. HOME - NIGHT', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Home Shopping Murder', 'Act 2', 'Tests, Allies, Enemies', 'INT. OFFICE - CONTINUOUS', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Home Shopping Murder', 'Act 2', 'Tests, Allies, Enemies', 'EXT. PARK - SAME', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Home Shopping Murder', 'Act 3', 'The Road Back', 'INT. BAR - DAY', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Home Shopping Murder', 'Act 3', 'The Road Back', 'EXT. BAR - NIGHT', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Home Shopping Murder', 'Act 3', 'The Road Back', 'INT. RESTAURANT - CONTINUOUS', 'thesis statement example', 'antithesis statement example', 'synthesis statement example'),
('heWtoH3WexPO84t5dJOiqWF1UlU2', 'Home Shopping Murder', 'Act 3', 'The Road Back', 'EXT. HOME - SAME', 'thesis statement example', 'antithesis statement example', 'synthesis statement example')

